"""add processing_started_at to manual

Revision ID: 21da8677f7df
Revises: 7d56728e6ea1
Create Date: 2026-09-07 18:33:30.537487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21da8677f7df'
down_revision: Union[str, Sequence[str], None] = '7d56728e6ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual', 'processing_started_at')
    # ### end Alembic commands ###
