"""initial schema

Revision ID: aed387bc41ac
Revises:
Create Date: 2026-08-31 09:34:05.686225

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aed387bc41ac"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "client",
        sa.Column("is_anonymous", sa.Boolean(), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        op.f("ix_client_session_id"), "client", ["session_id"], unique=False
    )
    op.create_table(
        "tenant",
        sa.Column(
            "type",
            sa.Enum("manufacturer", "public", name="tenant_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("allows_official_retrieval", sa.Boolean(), nullable=False),
        sa.Column(
            "branding",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("plan", sa.String(length=40), nullable=False),
        sa.Column("monthly_query_limit", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "api_key",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("key_hash", sa.String(length=128), nullable=False),
        sa.Column("prefix", sa.String(length=12), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index(
        op.f("ix_api_key_tenant_id"), "api_key", ["tenant_id"], unique=False
    )
    op.create_table(
        "manual",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "source",
            sa.Enum("official", "user_upload", name="manual_source", native_enum=False),
            nullable=False,
        ),
        sa.Column("revision", sa.String(length=40), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "ready",
                "failed",
                name="manual_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_manual_checksum"), "manual", ["checksum"], unique=False)
    op.create_index(op.f("ix_manual_status"), "manual", ["status"], unique=False)
    op.create_index(op.f("ix_manual_tenant_id"), "manual", ["tenant_id"], unique=False)
    op.create_table(
        "product",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand", sa.String(length=120), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "washing_machine",
                "dishwasher",
                "air_conditioner",
                "oven",
                "fridge",
                "tv",
                "other",
                name="product_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("public_token", sa.String(length=22), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "brand", "model", name="uq_product_identity"),
    )
    op.create_index(op.f("ix_product_brand"), "product", ["brand"], unique=False)
    op.create_index(op.f("ix_product_model"), "product", ["model"], unique=False)
    op.create_index(
        op.f("ix_product_public_token"), "product", ["public_token"], unique=True
    )
    op.create_index(
        op.f("ix_product_tenant_id"), "product", ["tenant_id"], unique=False
    )
    op.create_index(op.f("ix_product_type"), "product", ["type"], unique=False)
    op.create_table(
        "chunk",
        sa.Column("manual_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("page_from", sa.Integer(), nullable=False),
        sa.Column("page_to", sa.Integer(), nullable=False),
        sa.Column("section_path", sa.String(length=512), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', content)", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False
        ),
        sa.Column("applies_to", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("applies_condition", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["manual_id"], ["manual.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chunk_applies_to",
        "chunk",
        ["applies_to"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_chunk_content_tsv",
        "chunk",
        ["content_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_chunk_embedding_hnsw",
        "chunk",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(op.f("ix_chunk_language"), "chunk", ["language"], unique=False)
    op.create_index(op.f("ix_chunk_manual_id"), "chunk", ["manual_id"], unique=False)
    op.create_index(op.f("ix_chunk_tenant_id"), "chunk", ["tenant_id"], unique=False)
    op.create_table(
        "indexed_page",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_indexed_page_product_id"), "indexed_page", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_indexed_page_published"), "indexed_page", ["published"], unique=False
    )
    op.create_index(op.f("ix_indexed_page_slug"), "indexed_page", ["slug"], unique=True)
    op.create_table(
        "manual_product",
        sa.Column("manual_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["manual_id"], ["manual.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("manual_id", "product_id"),
    )
    op.create_table(
        "query_log",
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("manual_id", sa.UUID(), nullable=True),
        sa.Column("client_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("normalized_question", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column(
            "intent",
            sa.Enum(
                "error_code",
                "how_to",
                "safety",
                "out_of_scope",
                name="query_intent",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column(
            "citations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("resolved", sa.Boolean(), nullable=True),
        sa.Column("feedback", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("token_cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["manual_id"], ["manual.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_query_log_intent"), "query_log", ["intent"], unique=False)
    op.create_index(
        op.f("ix_query_log_normalized_question"),
        "query_log",
        ["normalized_question"],
        unique=False,
    )
    op.create_index(
        op.f("ix_query_log_product_id"), "query_log", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_query_log_resolved"), "query_log", ["resolved"], unique=False
    )
    op.create_index(
        op.f("ix_query_log_session_id"), "query_log", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_query_log_tenant_id"), "query_log", ["tenant_id"], unique=False
    )
    op.create_table(
        "escalation",
        sa.Column("query_log_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "no_answer",
                "safety",
                "user_request",
                name="escalation_reason",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open", "sent", "closed", name="escalation_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "contact_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["query_log_id"], ["query_log.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_escalation_status"), "escalation", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_escalation_tenant_id"), "escalation", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_escalation_tenant_id"), table_name="escalation")
    op.drop_index(op.f("ix_escalation_status"), table_name="escalation")
    op.drop_table("escalation")
    op.drop_index(op.f("ix_query_log_tenant_id"), table_name="query_log")
    op.drop_index(op.f("ix_query_log_session_id"), table_name="query_log")
    op.drop_index(op.f("ix_query_log_resolved"), table_name="query_log")
    op.drop_index(op.f("ix_query_log_product_id"), table_name="query_log")
    op.drop_index(op.f("ix_query_log_normalized_question"), table_name="query_log")
    op.drop_index(op.f("ix_query_log_intent"), table_name="query_log")
    op.drop_table("query_log")
    op.drop_table("manual_product")
    op.drop_index(op.f("ix_indexed_page_slug"), table_name="indexed_page")
    op.drop_index(op.f("ix_indexed_page_published"), table_name="indexed_page")
    op.drop_index(op.f("ix_indexed_page_product_id"), table_name="indexed_page")
    op.drop_table("indexed_page")
    op.drop_index(op.f("ix_chunk_tenant_id"), table_name="chunk")
    op.drop_index(op.f("ix_chunk_manual_id"), table_name="chunk")
    op.drop_index(op.f("ix_chunk_language"), table_name="chunk")
    op.drop_index(
        "ix_chunk_embedding_hnsw",
        table_name="chunk",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("ix_chunk_content_tsv", table_name="chunk", postgresql_using="gin")
    op.drop_index("ix_chunk_applies_to", table_name="chunk", postgresql_using="gin")
    op.drop_table("chunk")
    op.drop_index(op.f("ix_product_type"), table_name="product")
    op.drop_index(op.f("ix_product_tenant_id"), table_name="product")
    op.drop_index(op.f("ix_product_public_token"), table_name="product")
    op.drop_index(op.f("ix_product_model"), table_name="product")
    op.drop_index(op.f("ix_product_brand"), table_name="product")
    op.drop_table("product")
    op.drop_index(op.f("ix_manual_tenant_id"), table_name="manual")
    op.drop_index(op.f("ix_manual_status"), table_name="manual")
    op.drop_index(op.f("ix_manual_checksum"), table_name="manual")
    op.drop_table("manual")
    op.drop_index(op.f("ix_api_key_tenant_id"), table_name="api_key")
    op.drop_table("api_key")
    op.drop_table("tenant")
    op.drop_index(op.f("ix_client_session_id"), table_name="client")
    op.drop_table("client")
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS vector")
