"""add ingestion progress and conversation title

Revision ID: dc382e7369fc
Revises: 7bd07bb0009f
Create Date: 2026-09-21 14:14:52.228967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc382e7369fc'
down_revision: Union[str, Sequence[str], None] = '7bd07bb0009f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('title', sa.String(length=120), nullable=True))
    op.add_column('manual', sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual', 'progress')
    op.drop_column('conversation', 'title')
    # ### end Alembic commands ###
